// Demo fixture corpus consumed by the tool-tile "Load sample" buttons.
//
// Sources are generated by `make fixtures` (the `pivlib_fixtures` bin crate)
// under `tests/fixtures/`. Vite's `?url` import returns a bundled asset path;
// the LoadSampleBar component fetches the bytes on click.
//
// Everything here is *synthetic*. No real PII, no real biometrics, no real
// issuer signatures. The fingerprint slot is intentionally empty for now —
// see Phase 2A (cwsq_mem encode shim).

import rootCaUrl from '../../../tests/fixtures/root_ca.cer?url';
import pivCaUrl from '../../../tests/fixtures/piv_ca.cer?url';
import certPivAuthUrl from '../../../tests/fixtures/piv_auth.cer?url';
import certCardAuthUrl from '../../../tests/fixtures/card_auth.cer?url';
import certDigSigUrl from '../../../tests/fixtures/digital_signature.cer?url';
import certKeyMgmtUrl from '../../../tests/fixtures/key_management.cer?url';
import certContentSigUrl from '../../../tests/fixtures/content_signing.cer?url';
import csrUrl from '../../../tests/fixtures/piv_auth.csr?url';
import keyUrl from '../../../tests/fixtures/piv_auth.p8?url';
import crlUrl from '../../../tests/fixtures/revocation_list.crl?url';
import chainP7bUrl from '../../../tests/fixtures/chain.p7b?url';
import chuidUrl from '../../../tests/fixtures/chuid.bin?url';
import cccUrl from '../../../tests/fixtures/ccc.bin?url';
import securityObjectUrl from '../../../tests/fixtures/security_object.bin?url';
import portrait1x1Url from '../../../tests/fixtures/portrait_1x1.jpg?url';
import fingerprintWsqUrl from '../../../tests/fixtures/fingerprint_synthetic.wsq?url';
import pkcs12Url from '../../../tests/fixtures/demo.p12?url';

export interface Sample {
  label: string;
  description: string;
  url: string;
}

export async function fetchSampleBytes(sample: Sample): Promise<Uint8Array> {
  const res = await fetch(sample.url);
  if (!res.ok) {
    throw new Error(`failed to load sample "${sample.label}": HTTP ${res.status}`);
  }
  return new Uint8Array(await res.arrayBuffer());
}

export const SAMPLES = {
  // Encoding-detect tool: a handful of inputs in different shapes so the
  // cascade has something to discriminate on.
  encoding: [
    { label: 'X.509 cert (DER)', description: 'PIV Auth cert in raw DER — the detector lands on DER directly.', url: certPivAuthUrl },
    { label: 'PKCS#7 chain (DER)', description: 'Certs-only SignedData carrying the whole synthetic chain.', url: chainP7bUrl },
    { label: 'PKCS#10 CSR (DER)', description: 'A CSR signed by the PIV Auth EE key.', url: csrUrl },
  ],

  // Cert inspector: the 5 PIV roles. The classifier should light up
  // a different role for each.
  cert: [
    { label: 'PIV Authentication', description: 'EE cert · FPKI common-auth policy · classifies as PivAuth', url: certPivAuthUrl },
    { label: 'Card Authentication', description: 'EE cert · id-PIV-cardAuth EKU · classifies as CardAuth', url: certCardAuthUrl },
    { label: 'Digital Signature', description: 'EE cert · nonRepudiation KU + emailProtection EKU · classifies as DigitalSignature', url: certDigSigUrl },
    { label: 'Key Management', description: 'EE cert · keyEncipherment KU + emailProtection EKU · classifies as KeyManagement', url: certKeyMgmtUrl },
    { label: 'Content Signing', description: 'EE cert · id-PIV-content-signing EKU · classifies as ContentSigning', url: certContentSigUrl },
    { label: 'Root CA', description: 'Self-signed P-256 root of the synthetic chain.', url: rootCaUrl },
    { label: 'PIV CA', description: 'Intermediate signed by Root, issues the 5 EE certs above.', url: pivCaUrl },
  ],

  csr: [
    { label: 'PIV Authentication CSR', description: 'PKCS#10 request signed by the PIV Auth EE key.', url: csrUrl },
  ],

  crl: [
    { label: 'PIV CA revocation list', description: 'CRL issued by PIV CA, revoking the PIV Auth EE (serial 0x0301).', url: crlUrl },
  ],

  key: [
    { label: 'PIV Auth private key (PKCS#8)', description: 'P-256 PrivateKeyInfo. pivlib surfaces algorithm + curve only — no key material.', url: keyUrl },
  ],

  pkcs7: [
    { label: 'Demo chain (certs-only SignedData)', description: 'PKCS#7 envelope carrying Root CA + PIV CA + all 5 EE certs.', url: chainP7bUrl },
  ],

  chuid: [
    { label: 'Synthetic PIV CHUID', description: 'BER-TLV with FASC-N (agency=9999, credential=000042), GUID, 2030-01-01 expiration.', url: chuidUrl },
  ],

  ccc: [
    { label: 'Synthetic PIV CCC', description: 'GSC-IS card capability container with NIST PIV RID + data model 0x10.', url: cccUrl },
  ],

  securityObject: [
    { label: 'Synthetic Security Object', description: 'CMS SignedData wrapping an LDSSecurityObject with synthetic hashes for CHUID + portrait + fingerprint.', url: securityObjectUrl },
  ],

  portrait: [
    { label: '1×1 white-pixel JPEG', description: 'Tiny placeholder JPEG. Obviously not a real face — structurally valid input for the INCITS 385 encoder.', url: portrait1x1Url },
  ],

  fingerprint: [
    {
      label: '256×256 gradient WSQ',
      description: 'Synthetic 8-bit grayscale gradient compressed via NBIS at 0.75 bpp. Obviously not a real fingerprint — valid WSQ structure for the INCITS 378/381 encoders.',
      url: fingerprintWsqUrl,
    },
  ],

  pkcs12: [
    {
      label: 'Degenerate PFX (structure-only)',
      description: 'Minimal PKCS#12 with id-data AuthSafe and no MAC. pivlib reports structure, never decrypts. Real PFX bundles will show MAC algorithm + SafeBag types.',
      url: pkcs12Url,
    },
  ],
} as const satisfies Record<string, Sample[]>;
